#!/bin/bash
df -Ph| awk '{gsub("%","",$0);print }'| awk 'BEGIN{print "Below are partitions exceeding greater than 70%"}NR>1 && ($(NF-1) > 70){print $NF}'
echo "======================"
echo "ppppp"
echo "uuuuuu"
echo "----------------"
echo "test1"
echo "test2"
echo "test3jjjjjuuuuuuu"
